name: pconst310
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - alembic=1.8.1
  - alphalens-reloaded=0.4.3
  - aniso8601=9.0.1
  - appdirs=1.4.4
  - arrow-cpp=16.1.0
  - asttokens=2.0.5
  - async-timeout=4.0.3
  - attrs=23.1.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - bcolz-zipline=1.2.9
  - bcrypt=3.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - blinker=1.6.2
  - blosc=1.21.3
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.12.0
  - ca-certificates=2024.7.2
  - cachetools=5.3.3
  - certifi=2024.8.30
  - cffi=1.16.0
  - cfgv=3.4.0
  - charset-normalizer=3.3.2
  - clarabel=0.7.1
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - contourpy=1.2.0
  - cryptography=43.0.0
  - cvxpy=1.5.3
  - cvxpy-base=1.5.3
  - cycler=0.11.0
  - databricks-sdk=0.32.0
  - decorator=5.1.1
  - deprecated=1.2.13
  - distlib=0.3.8
  - docker-py=7.0.0
  - ecos=2.0.12
  - empyrical-reloaded=0.5.9
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - exchange-calendars=4.5.5
  - executing=0.8.3
  - filelock=3.13.1
  - flask=3.0.3
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozendict=2.4.2
  - frozenlist=1.4.0
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glog=0.5.0
  - google-auth=2.29.0
  - graphene=3.3
  - graphql-core=3.2.3
  - graphql-relay=3.2.0
  - greenlet=3.0.1
  - gunicorn=22.0.0
  - h2=4.1.0
  - h5py=3.11.0
  - hdf5=1.12.1
  - hpack=4.0.0
  - html5lib=1.1
  - hyperframe=6.0.1
  - icu=73.1
  - identify=2.5.5
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib_resources=6.4.5
  - intel-openmp=2023.1.0
  - intervaltree=3.1.0
  - ipython=8.25.0
  - iso3166=2.1.1
  - iso4217=1.9.20220401
  - itsdangerous=2.2.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - korean_lunar_calendar=0.2.1
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.9.1
  - libcxx=18.1.8
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libosqp=0.6.3
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libqdldl=0.1.7
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libta-lib=0.4.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.13.1
  - libxslt=1.1.41
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lru-dict=1.3.0
  - lxml=5.2.1
  - lz4-c=1.9.4
  - lzo=2.10
  - mako=1.2.3
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mlflow=2.16.0
  - mlflow-skinny=2.16.0
  - mlflow-ui=2.16.0
  - multidict=6.0.4
  - multipledispatch=0.6.0
  - multitasking=0.0.9
  - munkres=1.1.4
  - ncurses=6.4.20240210
  - networkx=3.3
  - nodeenv=1.7.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.15
  - opentelemetry-api=1.27.0
  - opentelemetry-sdk=1.27.0
  - opentelemetry-semantic-conventions=0.48b0
  - orc=2.0.1
  - osqp=0.6.3
  - packaging=24.1
  - pandas=2.2.2
  - pandas-datareader=0.10.0
  - paramiko=2.8.1
  - parso=0.8.3
  - patsy=0.5.6
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=3.10.0
  - pre-commit=3.8.0
  - pre_commit=3.8.0
  - prometheus_client=0.14.1
  - prometheus_flask_exporter=0.22.4
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=4.25.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pyarrow=16.1.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=4
  - pycparser=2.21
  - pyfolio-reloaded=0.9.7
  - pygments=2.15.1
  - pyluach=2.2.0
  - pynacl=1.5.0
  - pyopenssl=24.2.1
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - pytables=3.10.1
  - python=3.10.14
  - python-dateutil=2.9.0post0
  - python-interface=1.6.0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.1
  - pyu2f=0.1.5
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.1
  - qdldl-python=0.1.7.post0
  - qhull=2020.2
  - querystring_parser=1.2.4
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - rsa=4.7.2
  - scikit-learn=1.1.3
  - scipy=1.12.0
  - scs=3.2.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=72.1.0
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlalchemy=2.0.30
  - sqlite=3.45.3
  - sqlparse=0.4.4
  - stack_data=0.2.0
  - statsmodels=0.14.2
  - ta-lib=0.4.32
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.14
  - toolz=0.12.0
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ukkonen=1.0.1
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - utf8proc=2.6.1
  - virtualenv=20.26.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.3
  - wheel=0.43.0
  - wrapt=1.14.1
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.3
  - yfinance=0.2.28
  - zipline-reloaded=3.0.3
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip
  - pip:
    - -e ./src/alphalab
